Algoritmo "Lista 1 Exercicio 2"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Aldo Henrique
// Descrição   : conversão de graus para fahrenheit
// Autor(a)    : Carlos Henrique Aguiar de Oliveira
// Data atual  : 07/03/2018
Var
n1,F :real
Inicio
Escreval ("Valor da temperatura")
Leia (n1)
F<-(9*n1+160)/5
escreval ("O valor da temperatura em fahrenheit é")
escreval (F)
Fimalgoritmo