Algoritmo "Lista 3 exercicio 2"
// Disciplina  : LPOO
// Profesor(a) : AldO Henrique
// Descrição   : Maior e menor numero de 15
// Autor(a)    : Carlos Henrique Aguiar de Oliveira
// Data atual  : 09/04/2018
Var
tabuada, i :inteiro
Inicio
Escreval ("Digite o numero de 0 à 9 para o resultado:")
Leia (tabuada)
para i de 1 ate 10 faca
Escreval (tabuada, " x",i," =",tabuada*i)
fimpara
fimalgoritmo