Algoritmo "Lista 1 Exercicio 5"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Aldo Henrique
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Carlos Henrique Aguiar de Oliveira
// Data atual  : 07/03/2018
Var
n1, Q :inteiro
Inicio
Escreval (" digite o numero")
Leia (n1)
Q<- n1*n1
Escreva ("O quadrado do numero é" ,Q)
Fimalgoritmo