Algoritmo "lista 1 exercicio 3"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Aldo Henrique
// Descrição   : Volume de uma lata de óleo
// Autor(a)    : Carlos Henrique Aguiar de Oliveira
// Data atual  : 07/03/2018
Var
raio, altura, volume :real
Inicio

Escreval ("Raio")
Leia (raio)
Escreval ("Altura")
Leia (altura)
Volume<-PI*raio^2*altura
Escreval ("O volume da lata de óleo é", volume)

Fimalgoritmo